# Generated by Django 5.2.1 on 2025-06-25 07:42

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du produit', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('ean', models.CharField(blank=True, max_length=255, null=True)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='JadUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Adresse Mail')),
                ('fname', models.CharField(max_length=255, verbose_name='Prénom')),
                ('lname', models.CharField(max_length=255, verbose_name='Nom')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, help_text="Détermine si l'utilisateur peut se connecter à l'interface d'administration.", verbose_name='Statut staff')),
                ('is_assign', models.BooleanField(default=False, verbose_name='Magasins / Sociétés assignés')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('pays', django_countries.fields.CountryField(max_length=2)),
                ('users', models.ManyToManyField(blank=True, related_name='magasins', to=settings.AUTH_USER_MODEL, verbose_name='utilisateurs')),
            ],
            options={
                'verbose_name': 'Magasin',
                'verbose_name_plural': 'Magasins',
            },
        ),
        migrations.CreateModel(
            name='Mouvements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantité')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('magasin_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mouvements', to='accounts.magasin', verbose_name='magasin')),
                ('magasin_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mouvements_out', to='accounts.magasin', verbose_name='magasin')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mouvements', to='accounts.produit', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'Mouvement',
                'verbose_name_plural': 'Mouvements',
            },
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('pays', django_countries.fields.CountryField(max_length=2)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='societes', to=settings.AUTH_USER_MODEL, verbose_name='utilisateurs')),
            ],
            options={
                'verbose_name': 'Société',
                'verbose_name_plural': 'Sociétés',
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='accounts.societe', verbose_name='société'),
        ),
        migrations.AddField(
            model_name='magasin',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magasins', to='accounts.societe', verbose_name='société'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(verbose_name='quantité')),
                ('seuil', models.IntegerField(verbose_name='seuil')),
                ('alerte', models.BooleanField(default=False, verbose_name='alerte')),
                ('date', models.DateTimeField(auto_now=True)),
                ('obsolete', models.BooleanField(default=False, help_text='Cette option permet de retirer un produit du stock.', verbose_name='obsolete')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock', to='accounts.magasin', verbose_name='magasin')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock', to='accounts.produit', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'unique_together': {('produit', 'magasin')},
            },
        ),
    ]
