# Generated by Django 5.2.1 on 2025-05-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jaduser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text="Détermine si l'utilisateur peut se connecter à l'interface d'administration.", verbose_name='Statut staff'),
        ),
    ]
