# Generated by Django 5.2.1 on 2025-05-21 16:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_produit_societe_magasin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mouvements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantité')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('magasin_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mouvements', to='accounts.magasin', verbose_name='magasin')),
                ('magasin_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mouvements_out', to='accounts.magasin', verbose_name='magasin')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mouvements', to='accounts.produit', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'Mouvement',
                'verbose_name_plural': 'Mouvements',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantité')),
                ('seuil', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='seuil')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock', to='accounts.magasin', verbose_name='magasin')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock', to='accounts.produit', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'unique_together': {('produit', 'magasin')},
            },
        ),
    ]
